### ISSUE TITLE
command request malformed

### ISSUE THREAD

**Issue by StephenTurley** [SmartThingsCommunity/smartthings-cli#131]
I'm most likely entering the command  wrong:

```
smartthings devices:commands 9 1:2                                                     

[2020-12-21T23:22:03.632] [ERROR] cli - caught error Error: Request failed with status code 422: {"requestId":"60B2BB99-82E4-40BE-BBBF-4509D8905CA5","error":{"code":"ConstraintViolationError","message":"The request is malformed.","details":[{"code":"NotValidValue","target":"[0].capability","message":"1 is not a valid value.","details":[]}]}}
```

My intention with above command was to send a command to:

device: 9
capability: 1
command: 2

Which would turn a light on in my case.  The help screen says `COMMAND  the command [<component>]:<capability>:<command>([<arguments>])` which I interpreted as `component` and `arguments` are optional, while `capability` and `command` are required and must be separated with a `:`

**Comment by bbaraban** [comment]
I don't think their intention was to use numbers in place of the capability name/commands. I'm having trouble for another reason, any time I try a command with an argument I get an error.

For example,
`smartthings devices:commands 35 switchLevel:setLevel(50)
 »   Error: Unexpected argument: 50
 »   See more help with --help`

I can't for the life of me figure out how it wants the command formatted.

**Comment by j450h1** [comment]
I think you need to add the deviceID. here is an example for my TV:

``` ```smartthings devices:commands "{TVs_device_id_here}" "switch:on()"```

**Comment by Mist-Hunter** [comment]
I was struggling with this also. @j450h1 is right. Unlike all the other commands, it won't work with the device #, it needs the <Device id>. I didn't need the () in mine.

Example of working command.
./smartthings devices:commands bza4cefb-8d74-4284-aef1-a428da4e5a9b switch:off
