### ISSUE TITLE
Stdout and Output file from rules differ. Neither can be consumed as input.

### ISSUE THREAD

**Issue by orangebucket** [SmartThingsCommunity/smartthings-cli#161]
The output of the Rules API via the CLI can not be used as the input to the Rules API via the CLI.

### > smartthings rules:update RULEID --input=RULEID.yaml
[2021-02-18T13:07:37.646] [ERROR] cli - caught error Error: Request failed with status code 422: {"requestId":"4C153BEC-0CCB-42F6-92D0-ACC3E9C58FB6","error":{"code":"ConstraintViolationError","target":null,"message":"The request is malformed.","details":[{"code":"BodyMalformedError","target":"id","message":"Unknown field on line 1","details":[]}]}}

I guess that might be an API issue rather than specifically a CLI issue.

I also note that the standard output of `smartthings rules` ends with.

```
id: RULEID
status: Enabled
executionLocation: Cloud
```
The above is the same as the output of the API called directly. As mentioned it can not be consumed as input by the API with these lines present.

Howver the  `RULEID.yaml` is not the same as the standard output.

```
id: RULEID
status: Enabled
executionLocation: Cloud
locationId: LOCATIONID
locationName: LOCATION
```
That seems counter-intuitive.

**Comment by john-u** [comment]
This is indeed an issue across the SmartThings public API and not directly in the CLI. We have tested a number of other endpoints and they behaved inconsistently. We are planning to massage these cases as needed in the CLI and Core SDK (used by the CLI) going forward. The confusion with the location details being added to rule output is a good example where we could document the command better as well.
