### ISSUE TITLE
./smartthings edge:drivers returns strange list

### ISSUE THREAD

**Issue by veonua** [SmartThingsCommunity/smartthings-cli#206]
**Describe the bug**

subj

**To Reproduce**

edge:drivers

**Expected behavior**

see list of lua edge drivers

**Actual behavior**

───┬──────────────────────────────────────┬────────────────────────────────────────────────┬────────────────────────────┬─────────────┐
│ # │ Driver Id                            │ Name                                           │ Version                    │ Package Key │
├───┼──────────────────────────────────────┼────────────────────────────────────────────────┼────────────────────────────┼─────────────┤
│ 1 │ 4aee6bda-b9d9-41fa-b2d3-319d52a7b0a4 │ aonghus-mor/Aqara Wired Wall Switch No Neutral │ 2021-02-12T12:35:56.423355 │             │
│ 2 │ 2c728178-8b63-43f8-a45f-25c5412bd1e3 │ aonghus-mor/Aqara Wired Wall Switch No Neutral │ 2021-02-11T22:44:35.90924  │             │
└───┴──────────────────────────────────────┴────────────────────────────────────────────────┴────────────────────────────┴─────────────┘

I have removed all the aonghus-mor/ from groovy IDE

**Comment by john-u** [comment]
@veonua The Groovy IDE is not the source of the data for the `edge:drivers` command. The names listed would be the name specified in the [config file](https://developer-preview.smartthings.com/docs/devices/hub-connected/driver-components-and-structure#configuration-file) the first time you uploaded the driver. If you wish to change these, you can edit the config files and rerun [edge:drivers:package](https://github.com/SmartThingsCommunity/smartthings-cli#smartthings-edgedriverspackage-projectdirectory) on each to update them.

**Comment by veonua** [comment]
strange thing but I had this list before I uploaded any driver .
that is why I am wondering what it was

**Comment by john-u** [comment]
Our cloud team has identified an issue affecting a limited number of individuals in the Edge beta that causes some extra drivers as you have reported above. A fix has been implemented and you can safely delete them using the `edge:drivers:delete` command. Sorry for the confusion.
