### ISSUE TITLE
CLI commads list

### ISSUE THREAD

**Issue by Mariano-Github** [SmartThingsCommunity/smartthings-cli#207]
The command **smartthings edge: drivers: publish** is missing from the CLI command list in README.md FILE

**Comment by rossiam** [comment]
Thanks for the note! The `edge:drivers:publish` command is just an alias for the `edge:channels:assign` command so you can the documentation in the readme under that command:

https://github.com/SmartThingsCommunity/smartthings-cli#smartthings-edgechannelsassign-driverid-version

**Comment by Mariano-Github** [comment]
Thanks for the clarification
