### ISSUE TITLE
Bad URL for getting an access token in documentation 

### ISSUE THREAD

**Issue by paulvonbehren** [SmartThingsCommunity/smartthings-cli#230]
The documentation (smartthings-cli/packages/cli/doc/configuration.md) has a reference to URL 
https://smartthings.developer.samsung.com/docs/auth-and-permissions.html. This URL is now obsolete and I get forwarded to
a generic page that has no obvious way to get an access token. I found this discussed in a commuity forum discussion where someone recomended this URL https://account.smartthings.com/tokens. This URL worked for me; I was able to get a functional access token.

**Comment by john-u** [comment]
Thanks for the issue. We have updated the above link to point to the new docs portal in #232.
