### ISSUE TITLE
question: 

### ISSUE THREAD

**Issue by paulvonbehren** [SmartThingsCommunity/smartthings-cli#231]
**What is your question? Please describe.**
I'm writing a linux script to update a web page periodically with temperature/humity sensor values. I'd like each row to have room name (to identify the sensor), temperature and humidity. I can get list of sensors and properties (e.g. temperature) from  smartthings devices and  smartthings devices:status. In the ST app, get this info along with a room name for each sensor.  "smartthings locations:rooms" gives me a list of room name, location IDs, and room IDs. Is there a way to get a room ID for a device in the CLI?

**Additional context**
I apologize if I overlooked something obvious.

**Comment by john-u** [comment]
@paulvonbehren [smartthings devices](https://github.com/SmartThingsCommunity/smartthings-cli#smartthings-devices-id)  accepts an optional argument that can either be a device ID or an index into the list it returns. The data returned from this command on a specific device will include the roomId if it is assigned a room.

**Comment by paulvonbehren** [comment]
Thanks for the quich resonse. I see the Room ID now.
