### ISSUE TITLE
question: Why do I get an error on creating a custom capability?

### ISSUE THREAD

**Issue by varunszapp** [SmartThingsCommunity/smartthings-cli#242]
I am trying to create a custom capability using the CLI. I want to create a basic capability with a single string attribute and a setter command for the same. I have tried multiple names and followed the pattern rules from the smartthings-cli/packages/cli/src/commands/capabilities/create.ts  file. The error is not descriptive and I am not able to figure out why the error is caused. 

![error](https://user-images.githubusercontent.com/1976004/148641672-e363fcfb-bb44-422d-ac69-0c343ca69ae7.png)

**Comment by rossiam** [comment]
When you say "yes" to "Add a setter command for this attribute?", you automatically get a `setTestdata` command so your `setTestdata` basic command conflicts with this. I'll open a ticket to add a check for this case in the CLI to provide a better error message.

**Comment by varunszapp** [comment]
Okay, should have figured that one out! Thanks for the answer!
