### ISSUE TITLE
Opening CLI to a command prompt instead of running individual commands.

### ISSUE THREAD

**Issue by orangebucket** [SmartThingsCommunity/smartthings-cli#245]
**Is your feature request related to a problem? Please describe.**
I run the CLI from a Windows CMD shell. Generally I am using a knackered old laptop to do so. I find there is a significant startup overhead when using the CLI, even if no arguments are given and the CLI is just providing a list of commands. By significant I mean of the order of five or six seconds. Even on a newer and more powerful laptop there is still a noticeable pause of a second or so before anything happens. It is quite frustrating when you have a batch of rules to update.

**Describe the solution you'd like**
I am hoping it would be possible to open up the CLI to a command prompt so the startup overhead only happens once.

**Comment by john-u** [comment]
We are aware of the current startup performance of the CLI and have made some architectural changes that have improved it over time. Unfortunately, the team at OCLIF (the framework this CLI utilizes) [declined supporting a REPL mode](https://github.com/oclif/oclif/issues/209#issuecomment-465392932) as you describe. We are tracking a number of upstream issues (especially https://github.com/oclif/oclif/issues/606) which once resolved will allow us to continue making improvements in this area as we move out of pre-release.
​
In the meantime, you can try setting the env variable `OCLIF_TS_NODE=0` which will disable some bootstrapping unnecessary for our CLI. This provides a modest improvement that could be more noticeable on older hardware. Please be aware that disabling this flag may break some functionality if installing other 3rd party OCLIF plugins.
