### ISSUE TITLE
Can I interact with my phone with this?

### ISSUE THREAD

**Issue by danergo** [SmartThingsCommunity/smartthings-cli#250]
**What is your question? Please describe.**
Anyhow can I use this to "Find My Phone"? I'd like to be able to acquire my phone's (last) known location, but it's not showing up in between devices. (Devices are only for devices not joining to the phone via Bluetooth?)

**Comment by john-u** [comment]
Mobile device location is not available from our public API and thus not available from the CLI.

**Comment by danergo** [comment]
Hi, is this available now? What's the reason of banning mobile info from public API? It's mine, so why can't I locate it?

**Comment by danergo** [comment]
I see. Thank you. I can see my phones and smarttags precise location from a computer's browser. So it seems more data sent to cloud than just present/away.
