### ISSUE TITLE
What's the state ot this package?

### ISSUE THREAD

**Issue by laszukdawid** [SmartThingsCommunity/smartthings-cli#298]
I see that this package has never had any release (all are pre release) and since its creation two years ago, it is in constant beta state. What is the state of it? Is it usable?

**Comment by john-u** [comment]
We are still in beta status, but the CLI should be functional for the majority of use cases. It is a team priority to release v1.0.0 before the SmartThings Edge Platform is out of beta. We are actively working on a set of issues with a goal to wrap up and release v1.0.0 later this year.
