### ISSUE TITLE
How to change default user organization from the CLI?

### ISSUE THREAD

**Issue by maxelweb-vimar** [SmartThingsCommunity/smartthings-cli#340]
**What is your question? Please describe.**
Is it possible to change the default user organization from the config profiles? 

**Additional context**
Would it be possible to add this as a feature if it is not available?

**Comment by rossiam** [comment]
Forgot to update this issue. There is now an `organization` configuration option you can use to set this.

https://github.com/SmartThingsCommunity/smartthings-cli/blob/main/packages/cli/doc/configuration.md#configuration-options

**Comment by maxelweb-vimar** [comment]
Perfect, thank you!
