### ISSUE TITLE
help command is broken.

### ISSUE THREAD

**Issue by control-break** [SmartThingsCommunity/smartthings-cli#384]
When running the command "smartthings help" after using the windows msi installer, you receive the following response:
` »   Warning: help is not a smartthings command.
Did you mean apps? [y/n]:
 »   Error: Run smartthings help for a list of available commands.`

Version: @smartthings/cli/1.0.0-beta.15 win32-x64 node-v16.16.0 
OS: Win10 21H2 build 19044.1889

**Comment by rossiam** [comment]
We've added this to our list. We had decided to leave the `help` command out in favor of the `--help` flag so the fix may be just updating the error message. In any case, you can use `--help` already.

**Comment by control-break** [comment]
Sounds good, Thank you.

**Comment by rossiam** [comment]
Fixed with #399
