### ISSUE TITLE
Need windows zip file

### ISSUE THREAD

**Issue by toddaustin07** [SmartThingsCommunity/smartthings-cli#413]
Guys - I noticed you've started to post a tar file in the Release assets for the Windows executable instead of a zip.  A lot of Windows users aren't going be able to extract a tar file.  Can you please provide a zip file?

**Comment by john-u** [comment]
Sure, we can switch the Windows archive to zip format. In the meantime, anyone on Windows 10 and above should be able to `tar -xvzf smartthings-win-x64.tar.gz` from Powershell, Terminal or command prompt.
