### ISSUE TITLE
Device handler

### ISSUE THREAD

**Issue by Nick-R-Brandstrup** [SmartThingsCommunity/smartthings-cli#419]
Why cant I find the menu for device handler there I can put in my code for my new device Xiomi motion sensor? The hole setup look as at my phone in the app and all helpguides are showing me web version.

**Comment by john-u** [comment]
Unless we are misunderstanding the question, this doesn't seem CLI specific. However, we would still like to point you in the right direction to get support. Could you share the source of the help guide you referenced?

**Comment by orangebucket** [comment]
May I try to help (I am an end user) ?

If I understand the question correctly you have used https://account.smartthings.com/ in the expectation of reaching the IDE but you have found yourself at https://my.smartthings.com/ instead.

If you want to use the IDE, you need to go to https://graph.api.smartthings.com/ and then click on your Location on the Locations page to make sure you are taken to the correct shard for your account. For example, in the UK and EU area it may be https://graph-eu01-euwest1.api.smartthings.com/. It was avoiding the need to do this that led to https://account.smartthings.com/ redirecting to the correct shard in the first place, but it has reverted to the original method as the IDE is almost obsolete.

Please bear in mind that the DTH will likely only be usable to the end of the year and you should be looking for a replacement solution based on an Edge driver. I advise exploring https://community.smartthings.com/ for help in that direction.

The https://account.smartthings.com/ link will still appear in some documentation, especially old or third party documentation. Ironically if you get old enough documentation it will be https://graph.api.smartthings.com/ as things have gone full circle.
