### ISSUE TITLE
Text-to-speech to connected sonos speaker question: 

### ISSUE THREAD

**Issue by mydogtag** [SmartThingsCommunity/smartthings-cli#430]
**What is your question? Please describe.**
Is it possible to use the CLI to have text read aloud by a connected Sonos speaker similar to how the Android app works? I am able to play a sound file, but I was hoping that the TTS function would be built in. Perhaps this is a feature request?

**Additional context**
![image](https://user-images.githubusercontent.com/17838374/198898464-3cd24ed4-83d7-47b9-bba5-aa40fc51b6e8.png)

**Comment by rossiam** [comment]
The SmartThings CLI is a tool to help with developing applications and drivers for the SmartThings ecosystem.

For more general SmartThings support, please see [SmartThings Support](https://www.samsung.com/us/support/smart-home/smartthings/) or use the [SmartThings Community](https://community.smartthings.com/c/general-smartthings/56) forum.
