### ISSUE TITLE
Please check saved answers are valid, then say if they are being used.

### ISSUE THREAD

**Issue by orangebucket** [SmartThingsCommunity/smartthings-cli#445]
**Is your feature request related to a problem? Please describe.**
When a fellow user demonstrates a problem where they aren't being prompted to select a channel it is not unusual to completely forget that there is such a thing as 'saved answers', especially when they have saved a channel that either doesn't exist or doesn't belong to them and there is a prominent error message that distracts you.

**Describe the solution you'd like**
Let's consider the case of channels. I'd like you to check the saved channel is valid for the command being performed, and if it is I'd like you to say it is being used.

**Describe alternatives you've considered**
Alternatively just stop saving defaults. I'm easy ...

**Additional context**

**Comment by rossiam** [comment]
Added both a check for validity and a message in 1.0.1.
