### ISSUE TITLE
can't be installed on 64bit Debian 11

### ISSUE THREAD

**Issue by gevregbg** [SmartThingsCommunity/smartthings-cli#447]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Actual behavior**
A clear and concise description of what actually happens.

**Additional context**
Add any other context about the problem here. Please include output of `smartthings --version`. Screenshots can be helpful too.

**Comment by rossiam** [comment]
@gevregbg I just noticed you mentioned 64 bit Debian. Someone asked via another channel about 32 bit Debian and I confused that question with this one. I just tested this with 64-bit and the `smartthings-linux-x64.tar.gz` binary works for me.

Can you provide more detail? What is the error you are getting? Are you using ARM or Intel-based Debian 11?
