### ISSUE TITLE
Review the help text for --assign and --install.

### ISSUE THREAD

**Issue by orangebucket** [SmartThingsCommunity/smartthings-cli#465]
It might be easiest to skim through https://community.smartthings.com/t/edgeinstall-not-listing-all-my-drivers/256656 to get the background to this. If nothing else it validates issue #445 and PR #453 which is always satisfying.

The bottom line is that the help text for `edge:drivers:package` implies that `--assign` will prompt for the channel to assign the driver to. However what it really means is that it will run the equivalent of `edge:channels:assign {{driverId}}` which won't actually prompt if there is a valid saved channel.

I haven't tried it (or seen others try it) but I guess the same issue might apply with hubs and `--install`?

I can't immediately suggest better wording, but I do see how it might mislead.

**Comment by rossiam** [comment]
Good point. I'll update the wording on these flags.

**Comment by rossiam** [comment]
Wording updated in 1.1.0.
