### ISSUE TITLE
question: how to launch nextflix on smart tv using postman or cli

### ISSUE THREAD

**Issue by bradparks** [SmartThingsCommunity/smartthings-cli#466]
**What is your question? Please describe.**
I have the smarthings cli setup, and can turn my tv on, off, mute/unmute fine
but I can't see how to launch the built in apps, like Netflix, or make it search Netflix for something
Are there lots of example commands for things like this somewhere? In like a Postman collection or something?

NOTE: I have found this collection, but was looking for more TV oriented examples if possible: https://www.postman.com/smartthings?tab=overview

Or a nice simple wrapper script that shows common usages in bash?
Thanks in advance!

**Comment by Sitlintac** [comment]
The CLI implements the [SmartThings API](https://developer.smartthings.com/docs/api/public/). While the ability to issue commands to devices is included as part of the API, the details of which capabilities and commands are available to a specific device are outside of the scope of this project. You may be able to get more help for your particular situation at the [SmartThings Community forum](https://community.smartthings.com/).

**Comment by bradparks** [comment]
For anyone else that shows up here wondering the same thing, I don't think there is a direct API to do so, from what I can see?

Note I posted [a simliar question on the Samsung forums](https://us.community.samsung.com/t5/QLED-and-The-Frame/API-to-upload-photos-directly-to-the-Frame-or-USB/m-p/2491132#M22343), but no direct answer. If I find something, I will post back here.
