### ISSUE TITLE
Access certain features only(?) available in the app

### ISSUE THREAD

**Issue by erew123** [SmartThingsCommunity/smartthings-cli#477]
**Is your feature request related to a problem? Please describe.**
I am trying to get my Samsung HW-S61A sound bar integrated into my home automation (Openhab) via the SmartThings CLI. The sound bar has 2x features that are only(?) available through the phone app (not the remote control) and I cannot find a way to change their setting through the CLI. These features are "Night Mode" and "Voice enhancement", which are listed under "Advanced Sound Settings" in the phone app. (The equalizer and individual volume levels per speaker are also much easier to manage in the app, but these dont appear to be exposed via the CLI either).

I cannot, unless I'm missing it, find any way to view or change these individual settings through the CLI, but they must exist otherwise the phone app couldn't change them. For what it matters, I do not have a SmartThings hub, only the cloud option. 

Basic, overall volume level does appear to be supported. I'm guessing many other devices have similar issues where features are not exposed via API/Command line or other.

**Describe the solution you'd like**
Many people in the home automation communities are discussing the current changes in the SmartThings API e.g. []https://community.openhab.org/t/smartthings-binding-eol/138750 as are other communities (Home Assistant etc).

I think all these people, including myself, would like to be able to easily interact with SmartThings devices in a simplistic way, and have all device features/capabilities that the SmartThings app can offer, exposed, at least via the CLI, so that we can automate as needed. This would also include pulling current status of all these settings by JSON (for example) so that we could pull in changes back to our home automation system e.g. someone used the remote control to alter the volume of a device, which is reflected in the SmartThings app/cloud and then pulled back through a JSON query to our home automation (again, just an example of one scenario that would work).

If I'm wrong and these settings are exposed already (or other such settings for other devices) it would be great to have an example of how to both find and interact with these settings within the CLI. 

**Additional context**
Ultimately, I think people would love a local (linux/windows) daemon that could communicate with their SmartThings devices over the LAN and probably work with MQTT commands. I know this is probably beyond scope of current plans though.... but that would be amazing!!

**Other settings missing** "Sound Mode", "Equalizer/Tone", "Bass/Treble", "Woofer Volume", "Channel Volume" AKA "Side Speaker Volume" &"Rear Speaker Volume". 

For reference, here is the command line VS the settings I mentioned in the APP

![image](https://user-images.githubusercontent.com/35898566/216772610-b36e2b31-5cc7-4f03-a040-9d04cc2111a2.png)

Thanks!

**Comment by Sitlintac** [comment]
The good news, but also the bad news, is that you’re not wrong. Some devices have commands that can only be accessed by the app by design. Complex devices like TVs and soundbars are particularly likely to have app-only commands that can’t be accessed by the API and therefore also can’t be accessed by the CLI.

**Comment by erew123** [comment]
> The good news, but also the bad news...........

**Thanks for the reply, Genuinely appreciated!!** 

Not sure if you can comment, but I'm guessing this would be a decision from somewhere higher up the mgmt chain, something along the lines of "we want the app on peoples phones, so here's how we will do it" ....type of decision!

I don't understand the whole back end structure of the API etc (I'm technical, but not a developer), however, I noted that with my phone disconnected from my home network (so on mobile data) the phone app and all the features on my soundbar, still work (I can still control things such as Night Mode, Voice enhancement etc, that arent available through the CLI or Remote control). **So I assume there is still some kind of cloud service/system that is working over the internet with these, even if its not the API you mention?**

Is there anywhere you could point me in a direction where I could research/look into any possible ways to try access those other features (how the phone app accesses these features currently)?

Or, is there somewhere I and others could put in feature requests for this type of access? (unless I'm right that this is a mgmt decision)?

Thanks again!

**Comment by Sitlintac** [comment]
The decision of what can be accessed in a public API and what’s kept private is made by device designers, generally; I don’t think driving traffic to the app is a strong consideration. The bigger issues are flexibility and resources — once something’s in a public API, you have to commit resources to supporting it and can’t change your implementation in a way that breaks anyone’s off-label use — as well as security concerns and sometimes technical limitations. 

As far as where to put in a feature request, you might try posting in the [SmartThings community forum](https://community.smartthings.com/) if you haven't already. It's a long shot, but the forum has a big audience and you never know.
