### ISSUE TITLE
Login flow does not work on a headless machine

### ISSUE THREAD

**Issue by colin-nolan** [SmartThingsCommunity/smartthings-cli#480]
**Describe the bug**
The login flow on Linux attempts to use `xdg-open` to open a URL. This results in an error if the tool is being used on a headless machine, which likely does not have this software on the path.

**To Reproduce**
On a headless machine (e.g. on SSHing to a Raspberry Pi):
```
# No credentials have been configured at this point 
$ ./smartthings apps
logging in... done
node:events:505
      throw er; // Unhandled 'error' event
      ^

Error: spawn xdg-open ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:478:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (node:internal/child_process:289:12)
    at onErrorNT (node:internal/child_process:478:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn xdg-open',
  path: 'xdg-open',
  spawnargs: [ 'http://localhost:61974/start' ]
}
$ echo $? 
1
```

**Expected behavior**
The login flow should fall back to requesting that the user opens a given external URL in their browser (outside of the headless machine), and then it requests the code to be returned (e.g. via interactive input submission).

**Actual behavior**
Failure due to missing `xdg-open` command (and ability to conduct login on the machine CLI is being used on).

**Additional context**
```
$ ./smartthings --version
@smartthings/cli/1.1.2 linux-arm node-v16.16.0
```

**Comment by colin-nolan** [comment]
A hacky workaround is to put a "fake" `xdg-open` on the path and use it to gain the details required to complete the flow. 

For example, in a new directory `bin`, create the file `xdg-open` with content:
```
#!/usr/bin/env bash

set -euf -o pipefail

curl -Ls -o /dev/null -w %{url_effective} "$1" > /tmp/smartthings-login
```
Make the file executable and add it to the path: 
```
$ chmod +x bin/xdg-open
$ export PATH="${PATH}:${PWD}/bin"
```
Start the login flow (will not fail because it calls the fake `xdg-open` and waits for auth flow to complete):
```
$ ./smartthings apps
logging in... ⣻
```
In a different terminal (e.g. tmux; another SSH session), read the link to open in the file that was written:
```
$ cat /tmp/smartthings-login
https://account.smartthings.com/login?redirect=...
```
Copy and paste the URL into your browser and compelete the flow. The final page will redirect to a localhost address that your browser won't open correctly (because it's not on the localhost of the browser at that point). Copy the URL (contains the auth code) and feed it back via the same terminal you read the tmp file in:
```
$ curl http://localhost:61973/finish?code=YOURCODE
<html><body><h1>You can close the window.</h1></body></html>
```

Success:
```
$ ./smartthings apps
logging in... done
...
$ cat ~/.config/@smartthings/cli/credentials.json
{
    "default": {
        "accessToken": ...  
        ...
     }
}
```

**Comment by rossiam** [comment]
The default login flow isn't intended for use on a headless machine. We recommend using a PAT for this situation.

https://github.com/SmartThingsCommunity/smartthings-cli#authentication
