### ISSUE TITLE
firmware update

### ISSUE THREAD

**Issue by fawzib** [SmartThingsCommunity/smartthings-cli#506]
please add a firmware update to smartthings cli. specifically for z-wave devices

**Comment by Sitlintac** [comment]
Unfortunately, the SmartThings platform doesn't support updating firmware on Z-Wave devices directly.

**Comment by fawzib** [comment]
I know but it might be nice to add this feature to smart things cli at least. This comes with its own risks but better than going through pc controller route

**Comment by Sitlintac** [comment]
The CLI is an implementation of the [SmartThings API](https://developer.smartthings.com/docs/api/public/).  If the platform doesn't support a feature, then there's nothing for the CLI to provide access to.
