### ISSUE TITLE
question: Can the CLI be used to test device specific control commands?

### ISSUE THREAD

**Issue by oywino** [SmartThingsCommunity/smartthings-cli#520]
**What is your question? Please describe.**
I'm trying to build the correct CURL command to start the washing cycle on a Samsung washing machine using the ST REST_API.
I was hoping this CLI tool somehow could assist me in getting the syntax correct.
Here's my failing command:

`curl --location --request POST https://api.smartthings.com/v1/devices/4ffb6bXX-XXX-XXX-XXX-XX421a52a09c/commands -H 'Authorization: Bearer 9c2cfXXX-XXX-XXX-XXX-XXXXab0873f1' -H 'Content-Type: application/json' --data-raw '{"capability":"washerOperatingState", "command":"setMachineState", "arguments":["run"]}'`

(I've X'ed out some of the API Key numbers)

Have I completely misunderstood the purpose of this CLI tool, or can it in any way help me get things right?

**Comment by oywino** [comment]
This command worked just fine once I could figure out the correct syntax (no need for any tool);
`curl --location "https://api.smartthings.com/v1/devices/4ffXXb63-XXXX-XXXX-XXX-6742XXX2a09c/commands" --header "Content-Type: application/json" --header "Authorization: Bearer 9c2cf8cd-XXX-XXX-XXX-6c9XXX0873f1" --data "[{\"capability\":\"washerOperatingState\",\"command\":\"setMachineState\",\"arguments\":[\"run\"]}]"`

**Comment by bflorian** [comment]
Closing as resolved

**Comment by bflorian** [comment]
Closing as resolved
