### ISSUE TITLE
Trying to delete my capability, but is not working

### ISSUE THREAD

**Issue by Jhonattan-Souza** [SmartThingsCommunity/smartthings-cli#58]
I`ve tried many times, but isnt working.

Thanks!

![error](https://user-images.githubusercontent.com/19364782/85210955-f211dd00-b31a-11ea-921f-bc5d43e6637a.jpg)

**Comment by Ra7t0r** [comment]
Same here

**Comment by rossiam** [comment]
This has been fixed.
