### ISSUE TITLE
The value of "additionalProperties" MUST be a boolean or an object.

### ISSUE THREAD

**Issue by w35l3y** [SmartThingsCommunity/smartthings-cli#61]
According to [JSON schema version 4](https://tools.ietf.org/html/draft-fge-json-schema-validation-00#section-5.4.4), "additionalProperties" MUST be a boolean or an object.

Currently, it is only accepting "false"

**Comment by rossiam** [comment]
Technically, these APIs only support a subset of JSON schema and `false` is the only valid value for `additionalProperties`. I've opened a ticket to update the documentation.

**Comment by w35l3y** [comment]
Just for future reference...

https://smartthings.developer.samsung.com/docs/Capabilities/custom-capabilities.html#attributes

> 
> **Attributes**
> 
> Attributes are used to describe the state of a capability and stores its status. In the following example, a light can be a range of color temperatures ranging from warm to cool. The `schema` that defines the color temperature attribute is [JSON schema version 4](http://json-schema.org/specification-links.html#draft-4).


https://github.com/moikot/smartthings-go/blob/v1.0.0/models/argument.go#L31

> [JSON schema](http://json-schema.org/specification-links.html#draft-4) for the argument. The API implements JSON schema version 4. For more info regarding JSON schema, please read [Understanding JSON Schema](https://json-schema.org/understanding-json-schema/index.html).
