### ISSUE TITLE
Are changes not supposed to reflect in the Developer Workspace?

### ISSUE THREAD

**Issue by momo1** [SmartThingsCommunity/smartthings-cli#64]
Hi,

I've tried  creating a new profile using `smartthings deviceprofiles:create -j -i <myfile>.json`. It responds back with the JSON that includes the new profile's ID. And when I list it with `smartthings deviceprofiles` it shows up. However when I go Developer Workspace I don't see it. Is it not supposed to show up there?

Also if I create a profile from the UI and add a capability (even a standard one) to that profile from the CLI tool, the change doesn't show up in the UI even though the CLI will report that the profile does indeed have that capability.

I'm wondering if I'm missing some step to "commit" those changes or something like that? Or am I misusing this tool altogether? 

Thanks!

**Comment by rossiam** [comment]
Sorry for the long delay. It used to be true (when this issue was written) that the developer workspace did not reflect device profiles created directly with the API (which the CLI uses) but this has since been fixed.
