### ISSUE TITLE
feature request -> mssing data in devices output

### ISSUE THREAD

**Issue by TekniskSupport** [SmartThingsCommunity/smartthings-cli#99]
I am missing a few data points from devices when using the CLI vs what's available inte the IDE

Command:
`smartthings devices {n} [-y|-j]`

Would it be possible to add this data in the response?
- route
- metrics

**Comment by john-u** [comment]
The API for this data is deprecated and will be sunset along with the legacy platform. Our teams are discussing the possible options for exposing this data in the future.
